"""fix_models

Revision ID: 011ecd79da3a
Revises: ad60df1100dd
Create Date: 2026-03-17 15:29:34.516270

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "011ecd79da3a"
down_revision: Union[str, None] = "ad60df1100dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=255), nullable=False))
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "users", sa.Column("last_name", sa.String(length=255), nullable=False)
    )
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "full_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
