"""add userstatus

Revision ID: d97294d6ba68
Revises: 011ecd79da3a
Create Date: 2026-03-21 02:09:21.465233

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d97294d6ba68"
down_revision: Union[str, None] = "011ecd79da3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE userstatus AS ENUM ('USER', 'ADMIN')")
    op.add_column(
        "users",
        sa.Column("role", sa.Enum("USER", "ADMIN", name="userstatus"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
